




---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer
  namespace: sample-psp
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets", "ingresses"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["GET", "LIST"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-at-sample-psp
  namespace: sample-psp
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: developer
  apiGroup: ""
